---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-role-samba
      ansible.builtin.include_role:
        name: ansible-role-samba
      vars:
        create_guest_user: true
        server: true
