---
- name: Load var file with package names based on the OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install Samba client
  ansible.builtin.package:
    name: "{{ client_packages }}"

- name: Install and enable Samba server
  block:
    - name: Install Samba server packages
      ansible.builtin.package:
        name: "{{ server_packages }}"
    - name: Enable Samba service
      ansible.builtin.service:
        enabled: yes
        name: "{{ service_name }}"
    - name: Create Samba guest user
      ansible.builtin.user:
        comment: Samba guest account
        create_home: no
        home: /nonexistent
        name: "{{ guest_user }}"
        shell: /sbin/nologin
        system: yes
      when: create_guest_user
  when: server
